---
institution: Bard College -- Computer Science
location: Annandale-on-Hudson, New York  
deadline: 2025-10-15
active: true
type: Tenure Track
url: https://apply.interfolio.com/173483
---

The Bard College Computational Sciences program invites applications for an **open rank** Computer Science faculty position, 
to begin Fall 2026. We seek candidates who can contribute to the teaching and ongoing curricular development in our Computer Sciences major. 
The current faculty specializations are in computational biology, computer science education, artificial intelligence, natural language, 
spoken human/computer interfaces, human-robot interaction, data science, and algebraic and symbolic computation. 
While all fields will be considered, we particularly encourage applications from candidates who work in systems, graphics, cybersecurity, 
and networks. The innovative and interdisciplinary Computational 
Sciences program offers a B.A. in computer science, leads a minor in Data Analytics, and collaborated with several programs across the college 
including Environmental Studies, Experimental Humanities, and Mind, Brain, Behavior. Successful applicants will add to the set of recent hires 
within the expanding Computational Sciences program. Join our growing program and help shape new curricular offerings and research opportunities!
<br><br>
🗓️ Completed applications received by ***October 15, 2025*** will receive full consideration, and review of applications will continue until the position is filled.
