---
institution: Kenyon College 
location: Gambier, OH
deadline: 2025-11-1
active: true
type: Tenure Track
url: https://careers.pageuppeople.com/695/cw/en-us/job/493252/assistant-professor-interdisciplinary-program-in-computing

Kenyon College, a highly selective, nationally ranked liberal arts college in central Ohio, invites applications for a tenure-track position at the rank of Assistant Professor in the Interdisciplinary Program in Computing beginning in July 2026. 

We seek a dynamic teacher-scholar whose work bridges computing with other disciplines, whether in the sciences, 
social sciences, arts, or humanities. This is an open-field search. While candidates with doctorates in computer science 
or closely related fields are encouraged to apply, we also welcome applicants from other disciplines who have a strong 
record of computationally engaged scholarship and teaching in emerging fields such as digital humanities, computational social science, 
computationally-intensive natural sciences, or creative computing in the arts. We are especially interested in those who can help students connect
technical expertise with broader questions of culture, society, and domain-specific application.

<br> <br>
🗓️ Review of applications will begin on ***November 1, 2025***, and continue until the position is filled.
