---
institution: Ohio Wesleyan University
location: Delaware, OH
deadline: 2025-10-20
active: true
type: Tenure Track
url: https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=a2082ac8-6363-4a1c-92d0-adacd9e4f844&ccId=19000101_000001&jobId=537958&lang=en_US&source=CC4
---

The Department of Mathematics and Computer Science at Ohio Wesleyan University invites applications for a tenure-track position in Computer Science beginning August 2026. We seek an outstanding teacher-scholar committed to engaging undergraduates in both the classroom and the laboratory. We seek candidates who can teach generally across the breadth of Computer Sciences, but are especially interested in candidates who can also develop and teach courses in applied areas such as software development, machine learning, or similar subjects. The successful candidate will establish a dynamic research program that welcomes students at all levels of preparation, fostering student success.
...[Responsibilities include] Teach the standard teaching load of six courses per academic year (3 per semester), which includes lecture and laboratory sections where appropriate across a wide variety of Computer Science courses at all levels, and ranging across many topics and areas.
<br> <br>
🗓️ Review of applications will begin on ***Oct 20, 2025*** and continue until the position is filled.
