---
institution: Harvey Mudd College
location: Claremont, California
deadline: 2025-10-10
active: false
type: Tenure Track
url: https://academicjobsonline.org/ajo/jobs/30450
---

The Computer Science Department at Harvey Mudd College (HMC) is pleased to announce an opening for an assistant professor of artificial intelligence commencing July 1, 2026. Exceptional candidates at higher ranks are welcome to apply. Successful candidates should have completed a Ph.D. in a relevant field by the time of appointment. The candidate will be expected to provide students with vibrant AI research experiences and develop innovative AI curricula and programming that support AI education across all departments at HMC and beyond.  In addition to offering courses at the forefront of AI technological advances, such as Generative AI or Deep Learning, the candidate will be expected to have a clear vision for how their research and teaching address the ethics and social impacts of AI.  For example, in developing a curriculum, the candidate could create a course for all HMC students that teaches the theoretical foundations and the responsible use of AI across the STEM disciplines. They could also develop electives for specific HMC STEM majors, such as "AI for Engineering" and “AI for Scientific Discovery.”
<br> <br>
🗓️ We are currently reviewing applications for Zoom and on-site interview invitations and will continue reviewing applications until the positions are filled. Any applications received by ***October 10, 2025***, will receive full consideration.
