---
institution: Susquehanna University 
location: Selinsgrove, PA
deadline: 2025-11-03
active: true
type: Tenure Track
url: https://www.schooljobs.com/careers/susqu/jobs/5065923/assistant-professor-of-computer-science?
---

Susquehanna University invites applications for a tenure track position at the rank of Assistant Professor to start in August 2026.
Teaching duties will be 3 classes per semester and will include the entire range of Computer Science courses.
The area of research is open, but preference will be given to candidates with expertise in data science and machine learning. The candidate should have, or anticipate having by August 2026, a Ph.D. in Computer Science, with some background in Mathematics, or a Ph.D. in a related discipline, such as Data Science, Statistics, or Mathematics, with extensive Computer Science background and experience.
Demonstrated success or evidence of potential to excel in teaching and advising undergraduates is essential, as is ongoing scholarly productivity and institutional service.
<br> <br>
🗓️ Review of applications will begin on ***November 3, 2025***, and will continue until the position is filled. 
