---
institution: Seton Hall University
location: South Orange, NJ
active: true
type: Tenure Track
url: https://jobs.shu.edu/cw/en-us/job/497034
deadline: 2025-10-24
review: rolling
---

The Department of Mathematics and Computer Science at Seton Hall University invites applications for a full-time tenure-track position at the rank of assistant professor in Computer Science to start in August 2026.
<br><br>
Seton Hall University is located in South Orange, New Jersey, 14 miles from New York City. It is the oldest Catholic diocesan institution of higher education in the United States and is home to about 6,300 undergraduate and 4,700 graduate students. A vibrant and culturally diverse community, Seton Hall pursues academic excellence and ethical development in a collaborative environment and prepares its students to be servant leaders in their professional and community lives. Seton Hall University is an Equal Opportunity employer. It honors diversity and respects the religious commitments of all its employees. In turn, its employees respect Catholic beliefs and values, engage the Catholic Intellectual Tradition, and support the university’s mission as a Catholic institution of higher education.
<br><br>
🗓️ Review of applications is ***rolling*** and will continue
until the position is filled.