---
institution: Cal Poly
location: San Luis Obispo, CA, USA
deadline: 2025-12-10
active: true
type: Tenure Track
url: https://jobs.calpoly.edu/en-us/job/552135/assistant-professor-computer-science-and-software-engineering-ay-2627
---

The Computer Science and Software Engineering Department in the College of Engineering at California Polytechnic State University
in San Luis Obispo, California (Cal Poly) is excited to invite applications for a full-time, academic year, tenure-track faculty 
position at the Assistant Professor rank beginning Fall 2026.
Salary will be commensurate with education and experience of the individual selected. Qualified candidates with industry experience are encouraged to apply. Anticipated hiring range: $110,000 - $123,000 per year.
The successful candidate will be expected to teach undergraduate and master's level courses and support and expand curricular development in computer science and/or software engineering. As scholars, faculty should be engaged in scholarly work that is of very high quality as evidenced by external peer review. As colleagues, faculty are encouraged to perform service activities at all levels of the University.
Preference will be given primarily to candidates able to teach courses in areas of need and secondarily to candidates able to teach courses in additional areas of emphasis for the Computer Science and Software Engineering Department. Areas of need include software engineering, programming languages, operating systems, high-performance computing, full-stack mobile and web development, and databases. Additional areas of emphasis include privacy and security, artificial intelligence, game development, and data science.
<br> <br>
🗓️ For full consideration, candidates are encouraged to apply by the Review Begin Date, ***December 10, 2025***. Applications received after this date may be considered.
