---
institution: Grinnell College
location: Grinnell, IA. USA
deadline: 2025-10-03
active: true
type: Tenure Track
url: https://apply.interfolio.com/172155
---

The Department of Computer Science invites applications for a tenure-track appointment beginning Fall 2026. Assistant Professor (Ph.D.) preferred; Instructor (ABD) or Associate Professor possible. We seek candidates with an interest in teaching courses in systems or software design and development, and research involving any area of computer science. Candidates with degrees in closely related fields will also be considered. Candidates are expected to describe the ways they can support and engage with students and colleagues from historically underrepresented or marginalized groups. The teaching load is five courses (or equivalent; some classes with a significant lab component are credited as 1.5 courses) over two semesters; periodically one course will be Tutorial (a topical writing/critical thinking course for first-year students).  Additional information about our curriculum and faculty can be found at [https://www.cs.grinnell.edu](https://www.cs.grinnell.edu). 
<br> <br>
🗓️ We will begin reviewing applications on ***October 3, 2025*** and will continue until the positions are filled.

