---
institution: Barnard College
location: New York, NY. USA
deadline: 2025-10-08
active: true
type: Tenure Track
url: https://cs.barnard.edu/assistant-professor-computer-science-barnard-college
---

Barnard College invites applications for a tenure-track assistant professor in Computer Science to start July 1, 2026.  Barnard faculty are expected to engage in teaching, research, curriculum and program development, undergraduate advising, and mentoring of undergraduate research.  The successful hire will further the aims and vision of Barnard’s CS program and will embody strategic strengths for this growing program. There is opportunity to collaborate with faculty and students at both Barnard and Columbia.  We are seeking candidates who work in the following areas: Artificial Intelligence, including but not limited to Machine Learning, Responsible AI, and Computer Vision; Theoretical Computer Science, including Algorithms, Algorithmic Fairness, Game Theory, and Learning Theory; Systems and Networking, including Databases and Mobile Applications; and Data Science.  Within those areas, we encourage candidates who take a broad approach to computing—including “computing for good,” connections across multiple subareas of computer science, and research connections to another discipline.  Candidates must have a PhD in Computer Science or a related discipline, and should have a promising research agenda and record of scholarship, as well as a demonstrated commitment to undergraduate teaching, mentoring, and increasing participation in computer science.  Applications received by October 8, 2025 will receive full consideration. Review of applications will continue until the positions are filled.
<br> <br>
🗓️ Review of applications will begin on ***October 8, 2025***, and will continue until the position is filled.

