---
institution: St. Olaf College
location: Northfield, MN, USA
deadline: 2026-10-01
active: true
type: Tenure Track
url: https://fa-ewur-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3/job/2735/?utm_medium=jobshare&utm_source=External+Job+Share
---

The Department of Mathematics, Statistics, and Computer Science (MSCS) at St. Olaf College invites applications for a full-time, tenure track position in Computer Science at the Assistant Professor level, to begin August 2027. We are looking for candidates who can contribute broadly to our growing computer science program through teaching, research, and supervision of undergraduate research.
The normal teaching load is five courses per year. Teaching responsibilities include courses at all levels of a curriculum—from introductory programming courses to upper-level courses in one’s field of expertise—that is mindful of ACM/IEEE standards for undergraduate programs in computer science. Other important aspects of the position include the promotion of community-building and inclusivity within the MSCS Department and College, student advising, and other service work in the department and across the college.
A PhD in computer science or a closely related field is strongly preferred by the start date of appointment. All areas of specialization will be considered. We expect that the successful candidate will use their expertise to help provide a vision for the future as computer science continues to grow and evolve at St Olaf.

<br> <br>
🗓️ Review of applications begins ***October 1st, 2026*** and will continue 
until the position is filled. 