---
institution: University of Puget Sound
location: Tacoma, WA, USA
deadline: 2026-10-16
active: true
type: Tenure Track
url: https://www2.pugetsound.jobs/psc/HR92PRD/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_JBPST_FL&Action=U&FOCUS=Applicant&SiteId=3&JobOpeningId=8944&PostingSeq=1
---

The University of Puget Sound invites applications for a tenure-track Assistant Professor 
of Computer Science position to begin Fall 2027. The area of specialization is open. The 
successful candidate will teach courses across all levels of the Computer Science curriculum, 
from introductory courses to upper-level courses in their area of specialty. The standard 
teaching load is six units per academic year. Candidates are expected to maintain an active 
program of scholarship that engages undergraduate students and to contribute to student 
mentoring and advising, as well as university service.
<br><br>
A PhD in Computer Science or a closely related field is required by the time of 
appointment; ABD candidates will be considered. A strong commitment to undergraduate teaching, 
mentorship, and inclusive pedagogy is required.
<br><br>
Salary is commensurate with education and experience. Faculty salaries at the University of 
Puget Sound are based on a common salary scale based on experience. Assistant Professor 
salaries in 2026-2027 begin at  $85,177 (for an assistant professor in their first year of 
full-time college-level teaching with the terminal degree in their field still in progress) 
up through $97,917 annualized based on experience.
<br><br>
🗓️ Review of applications begins ***October 16, 2026*** and will continue 
until the position is filled. 
