---
institution: Reed College 
location: Portland, Oregon, USA
deadline: 2026-10-12
active: true
type: Tenure Track
url: https://www.reed.edu/dean_of_faculty/facsearch/positions/assistant-professor-tenure-stream-faculty-position-in-computer-systems.html
---

The Department of Computer Science at Reed College invites applications for an assistant professor tenure stream faculty position in computer systems beginning in the fall of 2027. Applicants should have a Ph.D. in computer science or a closely related field by the time of the appointment and should be committed to excellence in undergraduate teaching and in research. Applicants from any area of computer systems and applications, broadly construed, will be considered (e.g., networks, database systems, security, distributed computing, architecture, operating systems, robotics, etc.). The successful applicant will teach in the core computer science curriculum at all levels, will develop one or more courses in the applicant’s area(s) of expertise, and will work to foster a welcoming and engaged community. They will maintain an active research program, providing opportunities for student involvement, and they will advise several year-long senior thesis projects each year. The new hire will teach 5 course units per year over two semesters (3-2), including additional sections or lab sessions as part of the 5 units. 
<br> <br>
🗓️ Applications submitted by ***October 12, 2026*** are guaranteed full consideration, although review of applications will continue until the position is filled. 