---
institution: Davidson College
location: Davidson, NC, USA
deadline: 2026-10-05
active: true
type: Tenure Track
url: https://employment.davidson.edu/
---

The Department of Mathematics and Computer Science at Davidson College 
invites applications for a tenure-track appointment in Computer Science 
at the rank of Assistant Professor, beginning July 1, 2027.  
<br> <br>
We seek candidates with a strong commitment to improving access to computer 
science for all students, enthusiasm for teaching all levels of undergraduate 
students, and an independent research program that involves undergraduate 
researchers. The department welcomes applicants whose scholarship expands 
the expertise of our current faculty and opens new research opportunities 
for our majors in areas including, but not limited to, natural language 
processing, quantum computing, computer architecture, and AI safety/ethics. 
The successful candidate will teach an upper-level elective in their research 
area while also supporting our [core curriculum](https://catalog.davidson.edu/preview_program.php?catoid=28&poid=1799&returnto=1340).
<br> <br>
For a full job description and to apply, please visit 
<https://employment.davidson.edu>.
<br> <br>
🗓️ Review of applications begins ***October 5th, 2026*** and will continue 
until the position is filled. 
