---
institution: Bowdoin College
location: Brunswick, ME, USA
deadline: 2026-10-01
active: true
type: Tenure Track
url: https://careers.bowdoin.edu/postings/18104
---

Bowdoin College's Department of Computer Science invites applications for a
tenure-track Assistant Professor position beginning July 1, 2027. The department
seeks candidates whose research involves **artificial intelligence** or
interdisciplinary work involving AI, and especially encourages those whose work
intersects with **trustworthy AI** (e.g. explainability, interpretability, or
privacy in AI models) or **natural language processing**. The teaching load is
**2-2**, spanning all levels of the curriculum, including introductory courses as
well as advanced courses in the candidate's area of expertise. Bowdoin is
particularly interested in candidates dedicated to undergraduate teaching and with
promise of long-term successful research. A Ph.D. in Computer Science or a related
field is expected by the date of appointment. The advertised salary range is
$122,000–$128,000. Bowdoin offers a fully funded, year-long pre-tenure
sabbatical (after three years of teaching and successful reappointment), plus
regular, generously funded post-tenure sabbaticals.
<br> <br>
🗓️ Review of applications begins ***October 1st*** and will continue until the position
is filled.
