---
institution: Harvey Mudd College
location: Claremont, California
deadline: 2026-9-22
active: true
type: Tenure Track
url: https://academicjobsonline.org/ajo/jobs/32411
---
Harvey Mudd College (HMC) invites applications for the inaugural Jenna and
Paul Segal Endowed Professorship of Artificial Intelligence. 
The successful candidate will help build and advance the College’s human-centered, 
interdisciplinary vision for AI (hmc.edu/ai). They will join a collaborative 
faculty creatively exploring AI across the disciplines and through the College’s 
interdisciplinary centers. We seek an exemplary teacher-scholar who will explore 
the technical frontiers of AI intertwined with its human, ethical and societal 
implications, while preparing students to collaborate with AI systems in real-world 
contexts.  We anticipate hiring at the Assistant Professor level, but exceptional 
candidates at all ranks are encouraged to apply.
<br><br>
Successful candidates should have completed a Ph.D. in a relevant field by the 
time of appointment. The anticipated 9-month salary range for the assistant 
professor level is $115k – 135k, depending on experience. Faculty at HMC are generally 
eligible for a sabbatical leave every seven years of continuous service, with the option
of taking a half-year sabbatical following a successful third-year review.
In addition, Harvey Mudd is pleased to offer a robust benefits package, 
including faculty housing assistance and a dependent collegiate scholarship program. 
<br> <br>
🗓️ Review of applications begins ***September 22nd, 2026*** and will continue 
until the position is filled. 
