---
institution: Hillsdale College
location: Hillsdale, MI, USA
deadline: 2026-10-12
active: true
type: Tenure Track
url: https://apply.interfolio.com/191353
---

Hillsdale College invites applications for a tenure-track Assistant Professor or Associate Professor of Computer Science beginning in August 2027.  The teaching load is three courses per semester at all levels of the undergraduate curriculum. 
<br> <br>
Candidates should have completed a Ph.D. in Computer Science or a closely related field by the beginning of the appointment. Those with a master’s degree and strong qualifications may also be considered. The area of scholarly expertise is open. Candidates must demonstrate a strong commitment to excellence in teaching, an understanding of computer science vis-à-vis the liberal arts, and an ability to collaborate in the design and maintenance of the curriculum in a small department.
<br> <br>
🗓️ Review of applications will begin on ***October 12, 2026*** and continue until the position is filled or closed. 
