---
institution: Haverford College 
location: Haverford, PA
deadline: 2026-10-01
active: true
type: Tenure Track
url: https://www.haverford.edu/provost/news/tenure-track-assistant-professor-computer-science
---

Haverford College invites applications for a tenure-track position as Assistant Professor in the Department of Computer Science, starting in Fall semester 2027. The area of scholarly expertise is **open**, with the successful candidate demonstrating evidence of research productivity, vision, and long-term impact in their field. Teaching responsibilities include courses at all levels of the curriculum, in particular our core introductory sequence, upper-level electives that expand our range of advanced courses, and supervision of undergraduate research. The teaching load is five course units a year, which generally amounts to three or four regular courses per year once discussion or lab sections and senior thesis supervision are taken into account.
<br> <br>
The successful candidate should have completed a Ph.D. in Computer Science (or a closely related field) by September 1, 2027.
<br> <br>
🗓️ Applications should be submitted by ***October 1st, 2026***. 
